apiVersion: v1
kind: Service
metadata:
  name: logstash-service
spec:
  ports:
  - port: 1234
    targetPort: 1234
    protocol: TCP
    name: sensu-port
  type: NodePort
  selector:
    app: logstash
