apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
spec:
  ports:
  - port: 15672
    name: rabbit-management
    targetPort: 15672
    protocol: TCP
  - port: 5672
    name: rabbit
    targetPort: 5672
    protocol: TCP
  type: NodePort
  selector:
    app: rabbit
