apiVersion: v1
kind: Service
metadata:
  name: sensu-service
spec:
  ports:
  - port: 4567
    targetPort: 4567
    protocol: TCP
    name: sensu-port
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: uchiwa-port
  type: NodePort
  selector:
    app: sensu-server
