apiVersion: v1
kind: Service
metadata:
  name: uchiwa-service
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: uchiwa-port
  type: LoadBalancer
  selector:
    app: uchiwa-server
